In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\NGUYEN PHUONG BICH\Downloads\heart_disease_uci.csv")
del df['id']
del df['dataset']
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,63,Male,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,67,Male,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,67,Male,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,37,Male,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,41,Female,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,Female,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,62,Male,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,55,Male,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,58,Male,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,62,Male,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [34]:
df["sex"] = df["sex"].astype('string').apply(lambda x: 1 if x == "Male" else (0 if x == "Female" else -1))


df['cp'] = df['cp'].astype('string').apply(lambda x : 0 if  x == 'typical angina' else (1 if x == 'atypical angina' else (2 if x == 'non-anginal' else 3 if x == 'asymptomatic' else -1)))

df['fbs'] = df['fbs'].astype('string').apply(lambda x : 0 if x == 'FALSE' else (1 if x == 'TRUE' else -1))

df['restecg'] = df['restecg'].astype('string').apply(lambda x : 0 if x == 'normal' else (1 if x == 'st-t abnormality'else (2 if x == 'lv hypertrophy' else -1)))

df['exang'] = df['exang'].astype('string').apply(lambda x:0 if x == 'FALSE' else (1 if x == 'TRUE' else -1))

df['slope'] = df['slope'].astype('string').apply(lambda x : 0 if x == 'upsloping' else (1 if x == 'flat' else (2 if x == 'downsloping' else -1)))

df['thal'] = df['thal'].astype('string').apply(lambda x : 0 if x == 'normal' else (1 if x == 'fixed defect' else (2 if x == 'reversible' else (3 if x == 'not described' else -1))))

TypeError: boolean value of NA is ambiguous

In [29]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,63,1,0,145.0,233.0,-1,2,150.0,-1,2.3,2,0.0,1,0
1,67,1,3,160.0,286.0,-1,2,108.0,-1,1.5,1,3.0,0,2
2,67,1,3,120.0,229.0,-1,2,129.0,-1,2.6,1,2.0,-1,1
3,37,1,2,130.0,250.0,-1,0,187.0,-1,3.5,2,0.0,0,0
4,41,0,1,130.0,204.0,-1,2,172.0,-1,1.4,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,0,3,127.0,333.0,-1,1,154.0,-1,0.0,-1,NaN,-1,1
916,62,1,0,NaN,139.0,-1,1,NaN,-1,NaN,-1,NaN,-1,0
917,55,1,3,122.0,223.0,-1,1,100.0,-1,0.0,-1,NaN,1,2
918,58,1,3,NaN,385.0,-1,2,NaN,-1,NaN,-1,NaN,-1,0
919,62,1,1,120.0,254.0,-1,2,93.0,-1,0.0,-1,NaN,-1,1

In [5]:
df["sex"] = df["sex"].map({"Male": 1, "Female": 0})
df["exang"] = df["exang"].astype(int)

corr = df.corr()
corr

ValueError: cannot convert float NaN to integer